package com.bhamane.bridalstore.util
import android.content.*
import androidx.core.content.FileProvider
import com.bhamane.bridalstore.data.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.apache.poi.xssf.usermodel.XSSFWorkbook
import java.io.File
import java.io.FileOutputStream
import java.text.SimpleDateFormat
import java.util.*
object ExcelExporter { suspend fun export(context:Context,sales:List<SaleWithItems>,rentals:List<RentalEntity>):File=withContext(Dispatchers.IO){val wb=XSSFWorkbook();fun fmt(ms:Long)=SimpleDateFormat("dd-MM-yyyy",Locale.getDefault()).format(Date(ms));val s=wb.createSheet("Sales");listOf("Bill No","Date","Customer","Phone","Address","Items","Subtotal","Discount","Final Total").forEachIndexed{i,v->s.createRow(0).createCell(i).setCellValue(v)};sales.forEachIndexed{r,x->val row=s.createRow(r+1);val sale=x.sale;listOf(sale.billNumber,fmt(sale.date),sale.customerName,sale.phone,sale.address,x.items.joinToString(" | "){"${it.name} x${it.quantity} @ ${it.unitPrice}"},sale.subtotal.toString(),sale.discount.toString(),sale.finalTotal.toString()).forEachIndexed{i,v->row.createCell(i).setCellValue(v)}};val rs=wb.createSheet("Rentals");val rh=rs.createRow(0);listOf("Rental No","Item","Customer","Phone","Start","Return","Price","Status","Photo URI").forEachIndexed{i,v->rh.createCell(i).setCellValue(v)};rentals.forEachIndexed{r,x->val row=rs.createRow(r+1);listOf(x.rentalNumber,x.itemName,x.customerName,x.phone,fmt(x.startDate),fmt(x.returnDate),x.rentalPrice.toString(),x.status,x.photoUri?:"").forEachIndexed{i,v->row.createCell(i).setCellValue(v)}};val file=File(context.cacheDir,"Bhamane_Bills_${SimpleDateFormat("yyyyMMdd_HHmm",Locale.US).format(Date())}.xlsx");FileOutputStream(file).use{wb.write(it)};wb.close();file};fun share(context:Context,file:File){val uri=FileProvider.getUriForFile(context,context.packageName+".provider",file);context.startActivity(Intent.createChooser(Intent(Intent.ACTION_SEND).apply{type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet";putExtra(Intent.EXTRA_STREAM,uri);addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)},"Share Excel report"))}}
object WhatsAppReporter { fun send(context:Context,date:String,sales:Double,rentals:Double,bills:Int,rentalCount:Int){val msg="🌸 BHAMANE BRIDAL STORE\nDaily Business Report\n📅 $date\n\n💰 Sales: ₹$sales\n🧾 Bills: $bills\n👑 Rental Income: ₹$rentals\n📦 Rental Orders: $rentalCount\n\n📊 Total Business: ₹${sales+rentals}";val intent=Intent(Intent.ACTION_SEND).apply{type="text/plain";putExtra(Intent.EXTRA_TEXT,msg);setPackage("com.whatsapp")};try{context.startActivity(intent)}catch(_:Exception){context.startActivity(Intent.createChooser(Intent(Intent.ACTION_SEND).apply{type="text/plain";putExtra(Intent.EXTRA_TEXT,msg)},"Send daily report"))}}}
